# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 21:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('powwows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.CharField(default=datetime.datetime(2016, 4, 15, 21, 3, 5, 970484, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(default='foxnews.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tag1',
            field=models.CharField(default='sample', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tag2',
            field=models.CharField(default='sample', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tag3',
            field=models.CharField(default='sample', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tag4',
            field=models.CharField(default='sample', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tag5',
            field=models.CharField(default='sample', max_length=50),
            preserve_default=False,
        ),
    ]
